default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password: YOUR_PASSWORD
  username: YOUR_USERNAME

development:
  <<: *default
  database: rubylan

test:
  <<: *default
  database: rubylan_test